In [1]:
from IPython.display import display, HTML
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import statsmodels.api as sm

In [2]:
from TDSCoinbaseData import TDSCoinbaseData
from TDSTickGenerator import TDSTickGenerator
from TDSTransactionTracker import TDSTransactionTracker
import logging
logging.getLogger().setLevel(level=logging.ERROR)

import warnings
warnings.filterwarnings('ignore')

In [3]:
# instantiate our data interface
cb_obj = TDSCoinbaseData(cache_path='../data', notebook_logging=True)
# Set the start and end date
start_date = '20200701'
end_date = '20200930'

# List all of the products to be used in the strategy. Be sure to list all products you may use, these can't be updated later
products = ['BTC-USD', 'ETH-USD', 'BTC-EUR', 'ETH-EUR', 'LTC-USD', 'LTC-EUR']

In [4]:
MAX_TRAINNING_SIZE = 360
SIZE_LIMIT_REACHED = False

In [5]:
def append_ticks(tick, usd_btc, eth_btc, ltc_btc, 
                 max_r=SIZE_LIMIT_REACHED, scale_btc=1000000, scale_eth=10000, scale_ltc=10000):
    x = tick.p.btc_usd
    y = tick.p.eth_usd
    z = tick.p.ltc_usd
    usd_btc = usd_btc.append({'open': scale_btc/x.open, 'close': scale_btc/x.close, 
                      'volume': x.volume, 'datetime': tick.datetime}, ignore_index=True)
    eth_btc = eth_btc.append({'open': scale_eth * y.open/x.open, 'close': scale_eth *  y.close/x.close, 
                      'volume': y.volume, 'datetime': tick.datetime}, ignore_index=True)
    ltc_btc = ltc_btc.append({'open': scale_ltc * z.open/x.open, 'close': scale_ltc * z.close/x.close, 
                      'volume': z.volume, 'datetime': tick.datetime}, ignore_index=True)
    # Checks if size limit has been reached
    if (SIZE_LIMIT_REACHED or len(usd_btc.index) > MAX_TRAINNING_SIZE):
        usd_btc.iloc[1:]
        eth_btc.iloc[1:]
        ltc_btc.iloc[1:]
        max_r = True
        
    return(usd_btc, eth_btc, ltc_btc, max_r)

In [6]:
def calculate_time(pddatetime, numtime, plus=True):
    if plus:
        return pddatetime.to_pydatetime() + timedelta(minutes=numtime)
    else: 
        return pddatetime.to_pydatetime() - timedelta(minutes=numtime)

# frame -- dataframe
# minute -- the number of minutes to be predicted
def predict(frame, minute=3) :
    frame = frame.set_index('datetime')
    y = frame['open'].resample('1T').mean()
    l = frame['close'].resample('1T').mean()
    v = frame['volume'].resample('1T').mean()
    merged = pd.merge(y, l, on='datetime', how="outer")
    frame = pd.merge(merged, v, on='datetime', how="outer")

    mod = sm.tsa.VARMAX(frame[['open', 'close', 'volume']], order=(1, 0), error_cov_type='diagonal')
    results = mod.fit(maxiter=50, disp=False)
    #print(results.summary().tables[1])
    newtime = calculate_time(tick.datetime, minute)
    pred = results.get_prediction(start=pd.to_datetime(frame.index[-1]), end=newtime, dynamic=False)
    pred_ci = pred.conf_int()
    #print(pred.predicted_mean)
#     print(frame.iloc[-1])
    return (pred)

In [7]:
# Instantiate our transaction tracker. As required, we start with 1.0 BTC
trans_tracker = TDSTransactionTracker(start_date, end_date, holdings={'BTC' : 1.0})

# Instantiate a tick generator
tick_gen = TDSTickGenerator(cb_obj, products, start_date, end_date, interval=60)
tick = tick_gen.get_tick()

# Dataframe for history
d = {'open': [], 'close': [], 'volume': [], 'datetime': []}
usd_btc = pd.DataFrame(data=d)
eth_btc = pd.DataFrame(data=d)
ltc_btc = pd.DataFrame(data=d)

# loads initial value for testing
for i in range(0, 150):
    tick = tick_gen.get_tick()
    (usd_btc, eth_btc, ltc_btc, SIZE_LIMIT_REACHED) = append_ticks(tick, usd_btc, eth_btc, ltc_btc)

In [8]:
def get_coin_ratio(tick, holdings):
    btc = holdings.get("BTC") if "BTC" in holdings else 0
    eth = tick.p.eth_usd.close/tick.p.btc_usd.close * holdings.get("ETH") if "ETH" in holdings else 0
    ltc = tick.p.ltc_usd.close/tick.p.btc_usd.close * holdings.get("LTC") if "LTC" in holdings else 0
    usd = holdings.get("USD")/tick.p.btc_usd.close if "USD" in holdings else 0
    res = np.array([usd, eth, ltc, btc])
    return sum(res), res/sum(res)

In [9]:
def trade_ratio(curr_port, ideal_port, tick, trans_tracker, curr_hold_in_BTC):
    gap = (ideal_port - curr_port)[1:]
    gap_in_usd = gap * curr_hold_in_BTC * tick.p.btc_usd.close
    names = np.array(['ETH-USD', 'LTC-USD', 'BTC-USD'])
    names = names[np.argsort(gap_in_usd)]
    gap_in_usd = np.sort(gap_in_usd)
    # holdings = trans_tracker.get_holdings()
    
    for idx in range(len(names)):
        product = names[idx]
        change = gap_in_usd[idx]
        attr = getattr(tick.p, product.lower().replace('-', '_'))
        # curr_hold = trans_tracker.get_holdings().get(product) if product in 
        if change < 0:
            valid_vol = min(- change / attr.close, attr.volume * 0.5)
#             print(product[:3], trans_tracker.get_holdings().get(product[:3]))
            valid_vol = min(valid_vol, trans_tracker.get_holdings().get(product[:3])) // 0.000001 / 1000000
#             print(- change / attr.close, attr.volume * 0.5)
            trans_tracker.make_trade(tick, product, 'sell', valid_vol)
        elif change > 0:
            valid_amt = min(change, trans_tracker.get_holdings().get("USD"))
#             print(attr.volume)
            valid_amt = min(valid_amt, attr.volume * attr.close * 0.5) // 0.000001 / 1000000
#             print(valid_amt)
            trans_tracker.make_trade(tick, product, 'buy', valid_amt)


In [10]:
def trade_eth(tick, bu, eu, be, ee, has_usd):
        # Amount of ETH and BTC to trade at most due to volume restriction
        num_eth = min(tick.p.eth_usd.volume, tick.p.eth_eur.volume) / 2
        num_btc = num_eth * ee / be
        if (num_btc > min(tick.p.btc_usd.volume, tick.p.btc_eur.volume) / 2):
            num_btc = min(num_eth * ee / be, min(tick.p.btc_usd.volume, tick.p.btc_eur.volume) / 2)
            num_eth = num_btc * be / ee

        # Buy Bitcoin with USD
        trans_tracker.make_trade(tick, 'BTC-USD', 'buy', min(num_btc * bu, has_usd))
        # print(trans_tracker.get_holdings())
        # Sell Bitcoin for EUR
        trans_tracker.make_trade(tick, 'BTC-EUR', 'sell', min(num_btc, trans_tracker.get_holdings().get("BTC")))
        # print(trans_tracker.get_holdings())
        # Buy ETH with EUR
        trans_tracker.make_trade(tick, 'ETH-EUR', 'buy', min(num_eth * ee, trans_tracker.get_holdings().get("EUR")))
        # print(trans_tracker.get_holdings())
        # Sell ETH with USD
        trans_tracker.make_trade(tick, 'ETH-USD', 'sell', trans_tracker.get_holdings().get("ETH"))
        # print(trans_tracker.get_holdings())
        # Buy Bitcoin with USD
        trans_tracker.make_trade(tick, 'BTC-USD', 'buy', min(num_btc * bu, trans_tracker.get_holdings().get("USD")))
        # print(trans_tracker.get_holdings())

In [11]:
def trade_ltc(tick, bu, lu, be, le, has_usd):
        # Amount of LTC and BTC to trade at most due to volume restriction
        num_ltc = min(tick.p.ltc_usd.volume, tick.p.ltc_eur.volume) / 2
        num_btc = num_ltc * le / be
        if (num_btc > min(tick.p.btc_usd.volume, tick.p.btc_eur.volume) / 2):
            num_btc = min(num_ltc * le / be, min(tick.p.btc_usd.volume, tick.p.btc_eur.volume) / 2)
            num_ltc = num_btc * be / le

        # Buy Bitcoin with USD
        trans_tracker.make_trade(tick, 'BTC-USD', 'buy', min(num_btc * bu, has_usd))
        # print(trans_tracker.get_holdings())
        # Sell Bitcoin for EUR
        trans_tracker.make_trade(tick, 'BTC-EUR', 'sell', min(num_btc, trans_tracker.get_holdings().get("BTC")))
        # print(trans_tracker.get_holdings())
        # Buy LTC with EUR
        trans_tracker.make_trade(tick, 'LTC-EUR', 'buy', min(num_ltc * le, trans_tracker.get_holdings().get("EUR")))
        # print(trans_tracker.get_holdings())
        # Sell LTC with USD
        trans_tracker.make_trade(tick, 'LTC-USD', 'sell', trans_tracker.get_holdings().get("LTC"))
        # print(trans_tracker.get_holdings())
        # Buy Bitcoin with USD
        trans_tracker.make_trade(tick, 'BTC-USD', 'buy', min(num_btc * bu, trans_tracker.get_holdings().get("USD")))
        # print(trans_tracker.get_holdings())

In [19]:
def trades(tick, trans_tracker, usd_btc, eth_btc, ltc_btc, SIZE_LIMIT_REACHED, scale_btc=1000000, scale_eth=10000, scale_ltc=10000):
    
    # Get current prices 
    x_price = scale_btc / tick.p.btc_usd.close
    y_price = scale_eth * tick.p.eth_usd.close / tick.p.btc_usd.close
    z_price = scale_ltc * tick.p.ltc_usd.close / tick.p.btc_usd.close

    curr_hold_in_BTC, curr_port = get_coin_ratio(tick, trans_tracker.get_holdings())
    # print(count, curr_hold_in_BTC)
    
    # Get predicted values
    pred_usd = predict(usd_btc, 1)
    pred_eth = predict(eth_btc, 1)
    pred_ltc = predict(ltc_btc, 1)
    
    # Find which one increases the most
    changes = np.array([(pred_usd.predicted_mean["close"][-1]-x_price)/x_price, 
               (pred_eth.predicted_mean["close"][-1]-y_price)/y_price, 
               (pred_ltc.predicted_mean["close"][-1]-z_price)/z_price, 
                       0])
    print(curr_port, changes)
    # Obtain ideal portfolio
    if max(changes) - sum(curr_port * changes) > 0.005:
        ideal_port = np.zeros_like(changes)
        ideal_port[changes.argmax(0)] = 1

        # print(count, curr_port, ideal_port)
        trade_ratio(curr_port, ideal_port, tick, trans_tracker, curr_hold_in_BTC)
    
    (usd_btc, eth_btc, ltc_btc, SIZE_LIMIT_REACHED) = append_ticks(tick, usd_btc, eth_btc, ltc_btc)

In [24]:
hr=0
# count = 0
benchmark = 1.4
while tick is not None:
    curr_hold_in_BTC, curr_port = get_coin_ratio(tick, trans_tracker.get_holdings())
    # count += 1
    # print(count, curr_hold_in_BTC)
    if (tick and not hr == 0 and hr != tick.datetime.to_pydatetime().hour):
        print("Time:", tick.datetime.to_pydatetime().hour)
        print("holdings", trans_tracker.get_holdings())
        hr = tick.datetime.to_pydatetime().hour
        # 10% chance of attempting to trade
#         no trade for this tick
    if (not tick.p.btc_usd.volume and not tick.p.eth_usd.volume and not tick.p.ltc_usd.volume):
        continue

    bu = tick.p.btc_usd.close
    eu = tick.p.eth_usd.close
    lu = tick.p.ltc_usd.close
    be = tick.p.btc_eur.close
    ee = tick.p.eth_eur.close
    le = tick.p.ltc_eur.close

    has_usd = trans_tracker.get_holdings().get("USD")

    # Check exchange ratios for BTC - ETH and BTC - LTC
    be_ratio = (be * eu) / (ee * bu) * 100 - 100
    bl_ratio = (be * lu) / (le * bu) * 100 - 100

    # Check if it is an arbitrage opportunity for BTC - ETH or BTC - LTC
    if (be_ratio < benchmark and bl_ratio < benchmark):
        trades(tick, trans_tracker, usd_btc, eth_btc, ltc_btc, SIZE_LIMIT_REACHED)
        tick = tick_gen.get_tick()
        continue

    # Check which would guarantee larger profit
    if (be_ratio > bl_ratio):
        trade_eth(tick, bu, eu, be, ee, has_usd)
    else:
        trade_ltc(tick, bu, lu, be, le, has_usd)

    tick = tick_gen.get_tick()

[0. 0. 0. 1.] [-0.00202034 -0.01176276 -0.0103526   0.        ]
[0. 0. 0. 1.] [-0.00202034 -0.01176276 -0.0103526   0.        ]
[0. 0. 0. 1.] [-0.00202143 -0.01176384 -0.01035369  0.        ]
[0. 0. 0. 1.] [-0.00210259 -0.01188774 -0.00995635  0.        ]
[0. 0. 0. 1.] [-0.00266848 -0.01188225 -0.01051779  0.        ]
[0. 0. 0. 1.] [-0.003094   -0.01191189 -0.01046215  0.        ]
[0. 0. 0. 1.] [-0.00254785 -0.01184983 -0.01015912  0.        ]
[0. 0. 0. 1.] [-0.00254675 -0.01193583 -0.01039701  0.        ]
[0. 0. 0. 1.] [-0.00258952 -0.0119782  -0.01115565  0.        ]
[0. 0. 0. 1.] [-0.00254675 -0.01167452 -0.01111325  0.        ]
[0. 0. 0. 1.] [-0.00202363 -0.01167894 -0.01059462  0.        ]
[0. 0. 0. 1.] [-0.00202253 -0.01215657 -0.01035478  0.        ]
[0. 0. 0. 1.] [-0.00172533 -0.01225383 -0.01172943  0.        ]
[0. 0. 0. 1.] [-0.00133161 -0.01242936 -0.01205367  0.        ]
[0. 0. 0. 1.] [-0.0013689  -0.01259655 -0.01232832  0.        ]
[0. 0. 0. 1.] [-0.00111557 -0.01208534 -

[0. 0. 0. 1.] [-0.00461731 -0.01172231 -0.01030079  0.        ]
[0. 0. 0. 1.] [-0.00430914 -0.01141633 -0.01023386  0.        ]
[0. 0. 0. 1.] [-0.00374434 -0.01159771 -0.01039057  0.        ]
[0. 0. 0. 1.] [-0.00365332 -0.0115074  -0.01030016  0.        ]
[0. 0. 0. 1.] [-0.00377834 -0.01136964 -0.01042434  0.        ]
[0. 0. 0. 1.] [-0.00389349 -0.01174569 -0.00982069  0.        ]
[0. 0. 0. 1.] [-0.00383756 -0.01164657 -0.01024393  0.        ]
[0. 0. 0. 1.] [-0.00383427 -0.01159969 -0.01024066  0.        ]
[0. 0. 0. 1.] [-0.00407335 -0.00987028 -0.00999948  0.        ]
[0. 0. 0. 1.] [-0.00388033 -0.01103427 -0.00980761  0.        ]
[0. 0. 0. 1.] [-0.00415231 -0.01134796 -0.00959882  0.        ]
[0. 0. 0. 1.] [-0.00436507 -0.01147187 -0.00909097  0.        ]
[0. 0. 0. 1.] [-0.00443636 -0.01149898 -0.00916192  0.        ]
[0. 0. 0. 1.] [-0.00504721 -0.01171264 -0.00904989  0.        ]
[0. 0. 0. 1.] [-0.0050845  -0.01192432 -0.00908702  0.        ]
[0. 0. 0. 1.] [-0.00504941 -0.01162747 -

[0. 0. 0. 1.] [-0.00144896 -0.01341342 -0.01002489  0.        ]
[0. 0. 0. 1.] [-0.00144896 -0.0137602  -0.01002489  0.        ]
[0. 0. 0. 1.] [-0.00144896 -0.01389018 -0.01097931  0.        ]
[0. 0. 0. 1.] [-0.00144896 -0.0143232  -0.01145583  0.        ]
[0. 0. 0. 1.] [-0.00127349 -0.01427984 -0.01128212  0.        ]
[0. 0. 0. 1.] [-0.00108705 -0.01396595 -0.01204956  0.        ]
[0. 0. 0. 1.] [-0.00108705 -0.01470148 -0.01204956  0.        ]
[0. 0. 0. 1.] [-0.00041916 -0.01460479 -0.01162688  0.        ]
[0. 0. 0. 1.] [-0.00022176 -0.01436696 -0.0116695   0.        ]
[0. 0. 0. 1.] [ 0.00043516 -0.01380584 -0.01054406  0.        ]
[0. 0. 0. 1.] [-0.00019654 -0.01399616 -0.01140675  0.        ]
[0. 0. 0. 1.] [-0.00010003 -0.01429018 -0.01131132  0.        ]
[0. 0. 0. 1.] [ 6.44776677e-05 -1.44305568e-02 -1.11486616e-02  0.00000000e+00]
[0. 0. 0. 1.] [ 6.99611387e-05 -1.36900687e-02 -1.09052476e-02  0.00000000e+00]
[0. 0. 0. 1.] [ 0.00018511 -0.01452769 -0.01079136  0.        ]
[0. 0. 0

[0. 0. 0. 1.] [-0.00207517 -0.01120726 -0.00921153  0.        ]
[0. 0. 0. 1.] [-0.00244476 -0.01135557 -0.00909966  0.        ]
[0. 0. 0. 1.] [-0.00291085 -0.0108581  -0.00860408  0.        ]
[0. 0. 0. 1.] [-0.00297556 -0.01087864 -0.00866842  0.        ]
[0. 0. 0. 1.] [-0.00293498 -0.01127474 -0.00910757  0.        ]
[0. 0. 0. 1.] [-0.00257636 -0.01205223 -0.00970913  0.        ]
[0. 0. 0. 1.] [-0.00261255 -0.01152187 -0.0090268   0.        ]
[0. 0. 0. 1.] [-0.00270248 -0.01134947 -0.00911615  0.        ]
[0. 0. 0. 1.] [-0.00253359 -0.01135644 -0.00966667  0.        ]
[0. 0. 0. 1.] [-0.00253469 -0.01100867 -0.00966776  0.        ]
[0. 0. 0. 1.] [-0.00253359 -0.01109482 -0.00966667  0.        ]
[0. 0. 0. 1.] [-0.0026981  -0.01143231 -0.00983     0.        ]
[0. 0. 0. 1.] [-0.00260268 -0.01142492 -0.00973527  0.        ]
[0. 0. 0. 1.] [-0.00268055 -0.0107606  -0.00933388  0.        ]
[0. 0. 0. 1.] [-0.00260159 -0.0105513  -0.00925544  0.        ]
[0. 0. 0. 1.] [-0.00260159 -0.01033293 -

[0. 0. 0. 1.] [-0.00290208 -0.01111124 -0.01051065  0.        ]
[0. 0. 0. 1.] [-0.00290208 -0.01163451 -0.01051065  0.        ]
[0. 0. 0. 1.] [-0.00271674 -0.0113636  -0.01032673  0.        ]
[0. 0. 0. 1.] [-0.00288453 -0.01144275 -0.0100151   0.        ]
[0. 0. 0. 1.] [-0.00305781 -0.01113481 -0.00946919  0.        ]
[0. 0. 0. 1.] [-0.00325083 -0.01115173 -0.00966097  0.        ]
[0. 0. 0. 1.] [-0.00328812 -0.01110144 -0.00969802  0.        ]
[0. 0. 0. 1.] [-0.00295253 -0.01094309 -0.00984338  0.        ]
[0. 0. 0. 1.] [-0.00295362 -0.01111873 -0.00984447  0.        ]
[0. 0. 0. 1.] [-0.00277815 -0.01103197 -0.00967022  0.        ]
[0. 0. 0. 1.] [-0.00245682 -0.01088784 -0.00959045  0.        ]
[0. 0. 0. 1.] [-0.00257307 -0.01130838 -0.00970587  0.        ]
[0. 0. 0. 1.] [-0.00277596 -0.01137871 -0.00966804  0.        ]
[0. 0. 0. 1.] [-0.00277486 -0.0112032  -0.00990622  0.        ]
[0. 0. 0. 1.] [-0.00277815 -0.01133729 -0.00990948  0.        ]
[0. 0. 0. 1.] [-0.00237896 -0.01085427 -

[0. 0. 0. 1.] [-0.0039253  -0.01020461 -0.00937304  0.        ]
[0. 0. 0. 1.] [-0.0038924  -0.01017192 -0.00910051  0.        ]
[0. 0. 0. 1.] [-0.00368622 -0.00996704 -0.00889541  0.        ]
[0. 0. 0. 1.] [-0.00401193 -0.0100719  -0.00921943  0.        ]
[0. 0. 0. 1.] [-0.00401193 -0.0100719  -0.00921943  0.        ]
[0. 0. 0. 1.] [-0.00390556 -0.00996617 -0.00887368  0.        ]
[0. 0. 0. 1.] [-0.0038924  -0.01012816 -0.00910051  0.        ]
[0. 0. 0. 1.] [-0.0038924  -0.01012816 -0.00910051  0.        ]
[0. 0. 0. 1.] [-0.0038924  -0.01012816 -0.00886058  0.        ]
[0. 0. 0. 1.] [-0.0038924  -0.01012816 -0.00886058  0.        ]
[0. 0. 0. 1.] [-0.0038924  -0.01034691 -0.00886058  0.        ]
[0. 0. 0. 1.] [-0.0038924  -0.01074041 -0.00886058  0.        ]
[0. 0. 0. 1.] [-0.00310607 -0.01004695 -0.00831829  0.        ]
[0. 0. 0. 1.] [-0.00350526 -0.00969967 -0.0087154   0.        ]
[0. 0. 0. 1.] [-0.00330566 -0.01015771 -0.00923636  0.        ]
[0. 0. 0. 1.] [-0.00321683 -0.00980701 -

[0. 0. 0. 1.] [-0.00257088 -0.0104335  -0.00826605  0.        ]
[0. 0. 0. 1.] [-0.00257088 -0.01038982 -0.0077859   0.        ]
[0. 0. 0. 1.] [-0.00256978 -0.0114359  -0.00850485  0.        ]
[0. 0. 0. 1.] [-0.00256869 -0.01112962 -0.00850376  0.        ]
[0. 0. 0. 1.] [-0.00234057 -0.01129591 -0.00827701  0.        ]
[0. 0. 0. 1.] [-0.00227477 -0.01136145 -0.0082116   0.        ]
[0. 0. 0. 1.] [-0.00218265 -0.01148804 -0.0088393   0.        ]
[0. 0. 0. 1.] [-0.00204447 -0.01113324 -0.00798266  0.        ]
[0. 0. 0. 1.] [-0.00201266 -0.01145033 -0.00771102  0.        ]
[0. 0. 0. 1.] [-0.00198305 -0.01089799 -0.00768158  0.        ]
[0. 0. 0. 1.] [-0.00210698 -0.01054095 -0.00732443  0.        ]
[0. 0. 0. 1.] [-0.00213878 -0.0104852  -0.00711572  0.        ]
[0. 0. 0. 1.] [-0.00255662 -0.01024462 -0.00753147  0.        ]
[0. 0. 0. 1.] [-0.0018997  -0.01029178 -0.0075987   0.        ]
[0. 0. 0. 1.] [-0.00200718 -0.01035469 -0.00770557  0.        ]
[0. 0. 0. 1.] [-0.0018986  -0.0101597  -

[0. 0. 0. 1.] [-0.00597063 -0.00714594 -0.00780532  0.        ]
[0. 0. 0. 1.] [-0.00748626 -0.00755736 -0.00763087  0.        ]
[0. 0. 0. 1.] [-0.00799732 -0.00678716 -0.00814185  0.        ]
[0. 0. 0. 1.] [-0.00755645 -0.00705336 -0.00745955  0.        ]
[0. 0. 0. 1.] [-0.0073086  -0.00795338 -0.00914082  0.        ]
[0. 0. 0. 1.] [-0.00702346 -0.00832971 -0.00957791  0.        ]
[0. 0. 0. 1.] [-0.00729653 -0.00842622 -0.01081067  0.        ]
[0. 0. 0. 1.] [-0.00736234 -0.00840382 -0.01015617  0.        ]
[0. 0. 0. 1.] [-0.00650582 -0.0084735  -0.01026274  0.        ]
[0. 0. 0. 1.] [-0.00660891 -0.00809197 -0.00964518  0.        ]
[0. 0. 0. 1.] [-0.00665606 -0.00866747 -0.01065226  0.        ]
[0. 0. 0. 1.] [-0.00546505 -0.0079193  -0.00946605  0.        ]
[0. 0. 0. 1.] [-0.00575787 -0.00851938 -0.00951763  0.        ]
[0. 0. 0. 1.] [-0.00604192 -0.00765807 -0.0098006   0.        ]
[0. 0. 0. 1.] [-0.00636544 -0.00824534 -0.00964272  0.        ]
[0. 0. 0. 1.] [-0.00589715 -0.00795413 -

[0. 0. 0. 1.] [-0.00356448 -0.00831176 -0.01473693  0.        ]
[0. 0. 0. 1.] [-0.00429269 -0.00868539 -0.01427106  0.        ]
[0. 0. 0. 1.] [-0.00381672 -0.0088261  -0.01593347  0.        ]
[0. 0. 0. 1.] [-0.00384633 -0.00942554 -0.01667185  0.        ]
[0. 0. 0. 1.] [-0.00366977 -0.00968803 -0.01696983  0.        ]
[0. 0. 0. 1.] [-0.00392639 -0.00893522 -0.01698701  0.        ]
[0. 0. 0. 1.] [-0.0037246  -0.00969875 -0.01725989  0.        ]
[0. 0. 0. 1.] [-0.00340437 -0.01012454 -0.01741572  0.        ]
[0. 0. 0. 1.] [-0.00285163 -0.0101004  -0.01945856  0.        ]
[0. 0. 0. 1.] [-0.00287795 -0.01025765 -0.02018782  0.        ]
[0. 0. 0. 1.] [-0.00307974 -0.00997708 -0.01850855  0.        ]
[0. 0. 0. 1.] [-0.00300846 -0.00999376 -0.01843837  0.        ]
[0. 0. 0. 1.] [-0.00298543 -0.00997089 -0.01818048  0.        ]
[0. 0. 0. 1.] [-0.00314116 -0.01012553 -0.01856902  0.        ]
[0. 0. 0. 1.] [-0.00309949 -0.01034645 -0.01735088  0.        ]
[0. 0. 0. 1.] [-0.00371583 -0.01073987 -

[0. 0. 0. 1.] [-0.00374873 -0.00963515 -0.01633922  0.        ]
[0. 0. 0. 1.] [-0.00370815 -0.0092443  -0.01653545  0.        ]
[0. 0. 0. 1.] [-0.00374763 -0.0091959  -0.01633814  0.        ]
[0. 0. 0. 1.] [-0.00378053 -0.00931628 -0.01613423  0.        ]
[0. 0. 0. 1.] [-0.00384633 -0.00925023 -0.01525257  0.        ]
[0. 0. 0. 1.] [-0.00420166 -0.00907752 -0.01607721  0.        ]
[0. 0. 0. 1.] [-0.00352939 -0.00919802 -0.01541295  0.        ]
[0. 0. 0. 1.] [-0.00363138 -0.00877331 -0.01575039  0.        ]
[0. 0. 0. 1.] [-0.00348442 -0.00880257 -0.01560522  0.        ]
[0. 0. 0. 1.] [-0.00389349 -0.00881474 -0.01577271  0.        ]
[0. 0. 0. 1.] [-0.00396697 -0.00884398 -0.01584532  0.        ]
[0. 0. 0. 1.] [-0.00400645 -0.00892714 -0.01588433  0.        ]
[0. 0. 0. 1.] [-0.00345043 -0.00894417 -0.01580822  0.        ]
[0. 0. 0. 1.] [-0.0032936  -0.00870049 -0.01565333  0.        ]
[0. 0. 0. 1.] [-0.00309839 -0.00828695 -0.01522388  0.        ]
[0. 0. 0. 1.] [-0.0026981  -0.00876606 -

[0. 0. 0. 1.] [-0.00400316 -0.01015072 -0.0156444   0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01015072 -0.0156444   0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01015072 -0.0156444   0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01019448 -0.0156444   0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01015072 -0.0156444   0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01015072 -0.01588108  0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.00997564 -0.01588108  0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01006318 -0.01588108  0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01001941 -0.0156444   0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01001941 -0.0154076   0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01001941 -0.0154076   0.        ]
[0. 0. 0. 1.] [-0.00400316 -0.01001941 -0.01445928  0.        ]
[0. 0. 0. 1.] [-0.0044539  -0.01007349 -0.01490529  0.        ]
[0. 0. 0. 1.] [-0.00452299 -0.01001082 -0.01426159  0.        ]
[0. 0. 0. 1.] [-0.00495948 -0.01035733 -0.01493117  0.        ]
[0. 0. 0. 1.] [-0.00516566 -0.01029967 -

[0. 0. 0. 1.] [-0.00370705 -0.0104689  -0.01464081  0.        ]
[0. 0. 0. 1.] [-0.00370596 -0.01046782 -0.01463973  0.        ]
[0. 0. 0. 1.] [-0.00370705 -0.0104689  -0.01464081  0.        ]
[0. 0. 0. 1.] [-0.00370705 -0.01042518 -0.01464081  0.        ]
[0. 0. 0. 1.] [-0.00370705 -0.01051262 -0.0148779   0.        ]
[0. 0. 0. 1.] [-0.00370705 -0.01051262 -0.0148779   0.        ]
[0. 0. 0. 1.] [-0.00384195 -0.0106466  -0.01501129  0.        ]
[0. 0. 0. 1.] [-0.00467105 -0.01116422 -0.01583109  0.        ]
[0. 0. 0. 1.] [-0.00448132 -0.01066966 -0.01564349  0.        ]
[0. 0. 0. 1.] [-0.00448242 -0.01067075 -0.01517064  0.        ]
[0. 0. 0. 1.] [-0.00466008 -0.01054111 -0.0153464   0.        ]
[0. 0. 0. 1.] [-0.00466008 -0.01054111 -0.01439734  0.        ]
[0. 0. 0. 1.] [-0.00464034 -0.0103902  -0.01437779  0.        ]
[0. 0. 0. 1.] [-0.00497154 -0.01133167 -0.01470575  0.        ]
[0. 0. 0. 1.] [-0.00473795 -0.01092469 -0.01471186  0.        ]
[0. 0. 0. 1.] [-0.00492329 -0.01106516 -

[0. 0. 0. 1.] [-0.00562188 -0.00926278 -0.01511241  0.        ]
[0. 0. 0. 1.] [-0.00556485 -0.00920596 -0.01505592  0.        ]
[0. 0. 0. 1.] [-0.00555279 -0.00923786 -0.01480652  0.        ]
[0. 0. 0. 1.] [-0.00564601 -0.00928682 -0.01489887  0.        ]
[0. 0. 0. 1.] [-0.00561859 -0.00939122 -0.01487171  0.        ]
[0. 0. 0. 1.] [-0.00559666 -0.00932547 -0.01461242  0.        ]
[0. 0. 0. 1.] [-0.00562737 -0.00939996 -0.01464285  0.        ]
[0. 0. 0. 1.] [-0.0058467  -0.00970624 -0.0148602   0.        ]
[0. 0. 0. 1.] [-0.00566575 -0.00965764 -0.01468089  0.        ]
[0. 0. 0. 1.] [-0.00585219 -0.00936052 -0.01486564  0.        ]
[0. 0. 0. 1.] [-0.00616804 -0.00967526 -0.01494108  0.        ]
[0. 0. 0. 1.] [-0.006247   -0.01001724 -0.01596873  0.        ]
[0. 0. 0. 1.] [-0.00616146 -0.00993203 -0.01588402  0.        ]
[0. 0. 0. 1.] [-0.006247   -0.01001724 -0.01596873  0.        ]
[0. 0. 0. 1.] [-0.00586644 -0.01007683 -0.01606608  0.        ]
[0. 0. 0. 1.] [-0.00593883 -0.0102366  -

[0. 0. 0. 1.] [-0.00570084 -0.01135713 -0.02015009  0.        ]
[0. 0. 0. 1.] [-0.00546176 -0.01116315 -0.01991448  0.        ]
[0. 0. 0. 1.] [-0.00569755 -0.01131012 -0.02085127  0.        ]
[0. 0. 0. 1.] [-0.00562846 -0.01128516 -0.02078323  0.        ]
[0. 0. 0. 1.] [-0.00520952 -0.0116555  -0.02060537  0.        ]
[0. 0. 0. 1.] [-0.00520843 -0.01161073 -0.02083888  0.        ]
[0. 0. 0. 1.] [-0.00503515 -0.01178799 -0.0204337   0.        ]
[0. 0. 0. 1.] [-0.00489916 -0.01178391 -0.01959516  0.        ]
[0. 0. 0. 1.] [-0.00507792 -0.01152475 -0.01977128  0.        ]
[0. 0. 0. 1.] [-0.00504941 -0.01167115 -0.02115127  0.        ]
[0. 0. 0. 1.] [-0.00497483 -0.01137863 -0.0210779   0.        ]
[0. 0. 0. 1.] [-0.00503954 -0.01157399 -0.02043802  0.        ]
[0. 0. 0. 1.] [-0.00524572 -0.01151671 -0.020641    0.        ]
[0. 0. 0. 1.] [-0.00523585 -0.01133208 -0.01992687  0.        ]
[0. 0. 0. 1.] [-0.00517224 -0.01166214 -0.02080326  0.        ]
[0. 0. 0. 1.] [-0.00517224 -0.01148739 -

[0. 0. 0. 1.] [-0.00510534 -0.0105024  -0.01885738  0.        ]
[0. 0. 0. 1.] [-0.00500006 -0.01039769 -0.01875355  0.        ]
[0. 0. 0. 1.] [-0.00500006 -0.01044147 -0.01828236  0.        ]
[0. 0. 0. 1.] [-0.00499019 -0.01016891 -0.01827262  0.        ]
[0. 0. 0. 1.] [-0.00538171 -0.00985731 -0.01747942  0.        ]
[0. 0. 0. 1.] [-0.00522598 -0.00961456 -0.01685292  0.        ]
[0. 0. 0. 1.] [-0.0052161  -0.00964859 -0.01707956  0.        ]
[0. 0. 0. 1.] [-0.00562627 -0.00953055 -0.01724853  0.        ]
[0. 0. 0. 1.] [-0.00592786 -0.00952374 -0.01588985  0.        ]
[0. 0. 0. 1.] [-0.0062448  -0.00979565 -0.01549209  0.        ]
[0. 0. 0. 1.] [-0.00639505 -0.01025246 -0.01540358  0.        ]
[0. 0. 0. 1.] [-0.0062459  -0.00988452 -0.01525578  0.        ]
[0. 0. 0. 1.] [-0.00630841 -0.01007843 -0.01460487  0.        ]
[0. 0. 0. 1.] [-0.00635009 -0.01011994 -0.01535902  0.        ]
[0. 0. 0. 1.] [-0.00616694 -0.01068282 -0.01660034  0.        ]
[0. 0. 0. 1.] [-0.0060803  -0.01028978 -

[0. 0. 0. 1.] [-0.00457893 -0.01019781 -0.01621343  0.        ]
[0. 0. 0. 1.] [-0.00446597 -0.0100417  -0.01681116  0.        ]
[0. 0. 0. 1.] [-0.00451532 -0.01009077 -0.01638712  0.        ]
[0. 0. 0. 1.] [-0.00463376 -0.01090861 -0.01768511  0.        ]
[0. 0. 0. 1.] [-0.0042214  -0.01111084 -0.01727816  0.        ]
[0. 0. 0. 1.] [-0.0042225  -0.0111993  -0.01751519  0.        ]
[0. 0. 0. 1.] [-0.0047851  -0.01127753 -0.01807028  0.        ]
[0. 0. 0. 1.] [-0.00470395 -0.01110949 -0.01751843  0.        ]
[0. 0. 0. 1.] [-0.00464253 -0.01109218 -0.0174578   0.        ]
[0. 0. 0. 1.] [-0.00470285 -0.0110647  -0.01846045  0.        ]
[0. 0. 0. 1.] [-0.00461183 -0.01136754 -0.01813506  0.        ]
[0. 0. 0. 1.] [-0.00463705 -0.01139259 -0.0179242   0.        ]
[0. 0. 0. 1.] [-0.00462937 -0.01173428 -0.01838799  0.        ]
[0. 0. 0. 1.] [-0.00447145 -0.01170844 -0.01823225  0.        ]
[0. 0. 0. 1.] [-0.00424224 -0.01187363 -0.01800621  0.        ]
[0. 0. 0. 1.] [-0.00431791 -0.01194872 -

[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.51286595e-07] [ 0.00497767 -0.01644458 -0.01880341  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.51310178e-07] [ 0.00507198 -0.01605241 -0.01801141  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.51237510e-07] [ 0.00478136 -0.01616554 -0.01876195  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.51182666e-07] [ 0.00456202 -0.01603743 -0.01827625  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.51171149e-07] [ 0.00451596 -0.01582524 -0.01808775  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.51185134e-07] [ 0.00457189 -0.01581334 -0.01873332  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.51185134e-07] [ 0.00457189 -0.01619923 -0.01850002  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.51205701e-07] [ 0.00465414 -0.01607581 -0.01771902  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.51192538e-07] [ 0.0046015  -0.01612737 -0.01800414  0.  

[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50442822e-07] [ 0.00160314 -0.01803711 -0.01930209  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50465308e-07] [ 0.00169307 -0.01794894 -0.01874644  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50455985e-07] [ 0.00165578 -0.01729976 -0.01878296  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50454613e-07] [ 0.0016503  -0.01709066 -0.01902218  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50428837e-07] [ 0.00154721 -0.01702018 -0.01935685  0.        ]
[9.9999975e-01 0.0000000e+00 0.0000000e+00 2.5044337e-07] [ 0.00160533 -0.01683435 -0.01929994  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50431579e-07] [ 0.00155818 -0.01739552 -0.0191124   0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50421981e-07] [ 0.00151979 -0.01721872 -0.01914999  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50355894e-07] [ 0.00125549 -0.01717776 -0.01870725  0.      

[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50305986e-07] [ 0.00105589 -0.01698736 -0.01749695  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50329569e-07] [ 0.0011502  -0.01693769 -0.01740438  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50295292e-07] [ 0.00101312 -0.01690053 -0.01753893  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50289808e-07] [ 0.00099118 -0.0170509  -0.01756046  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50290082e-07] [ 0.00099228 -0.01700688 -0.01732468  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50307358e-07] [ 0.00106137 -0.01685314 -0.01749157  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50305438e-07] [ 0.0010537  -0.01681772 -0.01726439  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50307632e-07] [ 0.00106247 -0.01685206 -0.01749049  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50307358e-07] [ 0.00106137 -0.01685314 -0.01749157  0.  

[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50054527e-07] [ 5.02206431e-05 -1.72880525e-02 -2.33822304e-02  0.00000000e+00]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50054527e-07] [ 5.02206431e-05 -1.72880525e-02 -2.29178377e-02  0.00000000e+00]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50054253e-07] [ 4.91239488e-05 -1.72461702e-02 -2.19887987e-02  0.00000000e+00]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50054527e-07] [ 5.02206431e-05 -1.67722835e-02 -2.19877262e-02  0.00000000e+00]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50054527e-07] [ 5.02206431e-05 -1.69442667e-02 -2.19877262e-02  0.00000000e+00]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50054527e-07] [ 5.02206431e-05 -1.70302357e-02 -2.15220060e-02  0.00000000e+00]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.49982682e-07] [-0.00023711 -0.01671074 -0.02180314  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.49994747e-07] [-0.00018886 -0.01636202 -0.02128988  0.        ]
[9.99999

[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50117872e-07] [ 0.00030356 -0.01635112 -0.02057454  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50096209e-07] [ 0.00021692 -0.01622114 -0.02065938  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50060834e-07] [ 7.54446097e-05 -1.65324148e-02 -2.07978961e-02  0.00000000e+00]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50098402e-07] [ 0.00022569 -0.01638466 -0.02065078  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50101967e-07] [ 0.00023995 -0.01637064 -0.02063683  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50101967e-07] [ 0.00023995 -0.0164567  -0.02063683  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50099499e-07] [ 0.00023008 -0.01659545 -0.02064649  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50101967e-07] [ 0.00023995 -0.01658575 -0.02063683  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50101967e-07] [ 0.00023995 -0.01667176 -

[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.50604337e-07] [ 0.00224909 -0.01800341 -0.02030361  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.50609273e-07] [ 0.00226883 -0.01798407 -0.02028431  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.50604612e-07] [ 0.00225019 -0.01791672 -0.02030254  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.50609273e-07] [ 0.00226883 -0.01751301 -0.02075018  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.50608999e-07] [ 0.00226774 -0.01759977 -0.02075125  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.50595562e-07] [ 0.002214   -0.01743823 -0.01963832  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.50542638e-07] [ 0.00200234 -0.01721712 -0.02031178  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.50542364e-07] [ 0.00200124 -0.01743255 -0.02031285  0.        ]
[9.99999749e-01 0.00000000e+00 0.00000000e+00 2.50609273e-07] [ 0.00226883 -0.01747017 -0.02005122  0.  

[9.9999975e-01 0.0000000e+00 0.0000000e+00 2.5038030e-07] [ 0.00135309 -0.0173823  -0.02094656  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50377832e-07] [ 0.00134322 -0.01722038 -0.0211891   0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50364944e-07] [ 0.00129168 -0.01684172 -0.02054053  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50332037e-07] [ 0.00116008 -0.01671324 -0.02066927  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50283775e-07] [ 0.00096706 -0.01716046 -0.02062495  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50274177e-07] [ 0.00092867 -0.01698346 -0.02089562  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50281581e-07] [ 0.00095828 -0.01695438 -0.02086666  0.        ]
[9.9999975e-01 0.0000000e+00 0.0000000e+00 2.5028734e-07] [ 0.00098131 -0.01714646 -0.02084413  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50305986e-07] [ 0.00105589 -0.0170303  -0.02170267  0.        ]


[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50006813e-07] [-0.0001406  -0.0133783  -0.01702789  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50006813e-07] [-0.0001406  -0.01355151 -0.01796764  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50161199e-07] [ 0.00047683 -0.01376475 -0.01759601  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50171619e-07] [ 0.00051851 -0.01406955 -0.01755509  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50072626e-07] [ 0.0001226  -0.01441648 -0.01723935  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50053156e-07] [ 4.47371720e-05 -1.44932162e-02 -1.70808321e-02  0.00000000e+00]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50152972e-07] [ 0.00044393 -0.0140566  -0.0169236   0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50166409e-07] [ 0.00049767 -0.01400364 -0.0168708   0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50166409e-07] [ 0.00049767 -0.01404687 -

[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50132406e-07] [ 0.00036168 -0.01387827 -0.01559208  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50136245e-07] [ 0.00037704 -0.01369013 -0.01557697  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50154617e-07] [ 0.00045051 -0.01357442 -0.01550466  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50126373e-07] [ 0.00033755 -0.01368579 -0.01419944  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50192185e-07] [ 0.00060076 -0.01351281 -0.01488501  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50192185e-07] [ 0.00060076 -0.01381558 -0.01488501  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50192185e-07] [ 0.00060076 -0.01381558 -0.01535681  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50127195e-07] [ 0.00034084 -0.01376906 -0.01561258  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50181765e-07] [ 0.00055909 -0.01351064 -0.01492604  0.  

[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50170522e-07] [ 0.00051412 -0.01407388 -0.01331559  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50225366e-07] [ 0.00073346 -0.0138145  -0.01309928  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50225092e-07] [ 0.00073236 -0.01381559 -0.01310037  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50228382e-07] [ 0.00074552 -0.01384585 -0.01308739  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50227834e-07] [ 0.00074333 -0.01389124 -0.01332633  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50208913e-07] [ 0.00066766 -0.0136199  -0.01316418  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50048494e-07] [ 2.60933706e-05 -1.29971837e-02 -1.07105378e-02  0.00000000e+00]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50083869e-07] [ 0.00016757 -0.01320416 -0.01128463  0.        ]
[9.99999750e-01 0.00000000e+00 0.00000000e+00 2.50083869e-07] [ 0.00016757 -0.01285755 -

[1.93184005e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00437494 -0.01352946 -0.01411499  0.        ]
[1.93205287e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00448461 -0.01363812 -0.01422358  0.        ]
[1.93205287e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00448461 -0.01363812 -0.01422358  0.        ]
[1.93210821e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00451312 -0.01366637 -0.01425182  0.        ]
[1.9329323e-11 0.0000000e+00 0.0000000e+00 1.0000000e+00] [-0.00493754 -0.01343463 -0.01395928  0.        ]
[1.9329323e-11 0.0000000e+00 0.0000000e+00 1.0000000e+00] [-0.00493754 -0.01339112 -0.014197    0.        ]
[1.93293443e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00493864 -0.0137837  -0.01277008  0.        ]
[1.93341815e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00518759 -0.01368254 -0.01301707  0.        ]
[1.93363344e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00529836 -0.01396632 -0.01312696  0.        ]


[1.93660989e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00682715 -0.01478666 -0.01725362  0.        ]
[1.93589377e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00645976 -0.01459615 -0.01689009  0.        ]
[1.93624428e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00663961 -0.01486147 -0.01706806  0.        ]
[1.93564592e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00633254 -0.01429602 -0.01629047  0.        ]
[1.93604763e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00653872 -0.01450054 -0.01720487  0.        ]
[1.93660133e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00682276 -0.01482579 -0.01701259  0.        ]
[1.93703554e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00704539 -0.01500316 -0.01699618  0.        ]
[1.93703554e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00704539 -0.01500316 -0.01699618  0.        ]
[1.93703554e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00704539 -0.01500316 -0.01699618  0.  

[1.93314962e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00504941 -0.01376303 -0.01596843  0.        ]
[1.93325404e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00510315 -0.0138163  -0.01602158  0.        ]
[1.93330306e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00512837 -0.0138413  -0.01509837  0.        ]
[1.93331371e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00513385 -0.01402065 -0.0151038   0.        ]
[1.93379975e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.0053839  -0.01418153 -0.01535134  0.        ]
[1.93386585e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.0054179  -0.01421523 -0.01538499  0.        ]
[1.93384666e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00540803 -0.01442273 -0.01537522  0.        ]
[1.93379975e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.0053839  -0.01439882 -0.01535134  0.        ]
[1.93454206e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00576555 -0.01455981 -0.01572916  0.  

[1.94159892e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00937916 -0.01055044 -0.0159878   0.        ]
[1.94140764e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00928155 -0.01080457 -0.01612867  0.        ]
[1.9407889e-11 0.0000000e+00 0.0000000e+00 1.0000000e+00] [-0.0089657  -0.01062104 -0.015815    0.        ]
[1.94201602e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00959191 -0.01076294 -0.01643688  0.        ]
[1.94144202e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.0092991  -0.01047047 -0.01471746  0.        ]
[1.94080608e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00897448 -0.01036609 -0.01558582  0.        ]
[1.9402049e-11 0.0000000e+00 0.0000000e+00 1.0000000e+00] [-0.0086674  -0.01032324 -0.01528079  0.        ]
[1.94028861e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00871017 -0.01067349 -0.01532328  0.        ]
[1.93976284e-11 0.00000000e+00 0.00000000e+00 1.00000000e+00] [-0.00844148 -0.01062496 -0.01505638  0.        ]


KeyboardInterrupt: 

In [26]:
print(trans_tracker.get_sharpe_ratio())

RISK FREE DAILY RETURN : 
0.00016438356164383562
ACTUAL DAILY RETURN : 
0.00015141235671801436
EXCESS STD : 
0.002119091538562206
-0.0061211159073487524


In [27]:
trans_tracker.get_holdings()

{'BTC': 1.0138204709656093, 'USD': 1.7780439520720392e-07}

In [25]:
trans_tracker.get_trades()

[{'date': '20200701',
  'timestamp': 1593591840,
  'side': 'sell',
  'size': 1.0,
  'price': 9165.5,
  'product': 'BTC-USD',
  'holdings': {'BTC': 0.0, 'USD': 9149.0021}},
 {'date': '20200702',
  'timestamp': 1593702660,
  'side': 'buy',
  'size': 1.0085045608117418,
  'price': 9071.85,
  'product': 'BTC-USD',
  'holdings': {'BTC': 1.0066892526022806, 'USD': 0.0}},
 {'date': '20200704',
  'timestamp': 1593884100,
  'side': 'sell',
  'size': 1.006689,
  'price': 9166.97,
  'product': 'BTC-USD',
  'holdings': {'BTC': 2.5260228064816204e-07, 'USD': 9211.676944177805}},
 {'date': '20200705',
  'timestamp': 1593928800,
  'side': 'buy',
  'size': 1.0156483854571516,
  'price': 9069.75,
  'product': 'BTC-USD',
  'holdings': {'BTC': 1.0138204709656093, 'USD': 1.7780439520720392e-07}}]

In [ ]:
trans_tracker.dump_trades('run_2.json')

In [17]:
curr_hold_in_BTC, curr_port = get_coin_ratio(tick, trans_tracker.get_holdings())
curr_hold_in_BTC

0.989925687965194